fun main (args : Array<String>){
    println("Types of variable")
    println("Long type (64 bits) :")
    println("max. value - " + Long.MAX_VALUE)
    println("min. value - " + Long.MIN_VALUE + "\n")
    println("Int type (32 bits) :")
    println("max. value - " + Int.MAX_VALUE)
    println("min. value - " + Int.MIN_VALUE + "\n")
    println("Short type (16 bits) :")
    println("max. value - " + Short.MAX_VALUE)
    println("min. value - " + Short.MIN_VALUE + "\n")
    println("Byte type (8 bits) :")
    println("max. value - " + Byte.MAX_VALUE)
    println("min. value - " + Byte.MIN_VALUE + "\n")
    println("Types of floating-point variable")
    println("Double type (64 bits) :")
    println("max. value - " + Double.MAX_VALUE)
    println("min. value - " + Double.MIN_VALUE + "\n")
    println("Float type (32 bits) :")
    println("max. value - " + Float.MAX_VALUE)
    println("min. value - " + Float.MIN_VALUE + "\n")
}